### ISSUE TITLE
Feature request: collapsing/expandable subflows which are grouping of nodes

### ISSUE THREAD

**Issue by mick-d** [retejs/comment-plugin#8]
It would be super useful:
* to be able to group nodes to create a single node with the inputs and outputs inferred from the underlying nodes, and to be able to do that hierarchically (i.e. a subflow can also contain a node which is a subflow)
* to expand and collapse this node-subflow at will in the GUI (the general flow will be more detailed or less detailed on the canvas as a result)
* to be able to put any of these node-subflows in a menu of nodes (when the user put a node-subflow on the canvas he can then expand it as describe above)

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/302#issuecomment-515172546

**Comment by mick-d** [comment]
Examples from other software (in case they are useful):
- Unreal engine (Collapsing Nodes section): https://docs.unrealengine.com/en-US/Engine/Blueprints/BP_HowTo/CollapsingGraphs/index.html
-  Blender: https://docs.blender.org/manual/en/latest/editors/node_editor/nodes/groups.html

**Comment by alessiapacca** [comment]
hey @Ni55aN ! Any plans of including this feature in the library? It would be really really useful to maintain tidy flows. 
In Unreal Engine for example, in blueprints, nodes can be collapsed together, and the user can click on the "collapsed" node to open a new editor with the subflow inside. 
![image](https://user-images.githubusercontent.com/48483036/202423341-116e8b65-5ab1-4d70-8b0b-b93a1511eb6f.png)
https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/Blueprints/BP_HowTo/CollapsingGraphs/

**Comment by Ni55aN** [comment]
Personally, I did not need such a feature, since I solved a similar problem using the modules plugin (but be careful, it will not be supported in version 2).
Moreover, the unresolved issue is what to do with the connections that are between the collapsed nodes and the rest? I think it depends a lot on the type of your graph. For example, in UE 4 there are two types of connections (control flow and data, as it done in `task plugin`), but someone doesn't have such connections and the purpose of the connections is different.
That's why I think that solutions should be individual, and here's how in theory this can be achieved:

- remove the collapsible nodes
- create a Collapsed node instead and put an information about collapsed nodes
- *handle connections between collapsed nodes and outer nodes
- *create nested Engine and process collapsed nodes separately including connections from point above (the same, in the  version 2 the concept of the engine will be revised)

**Comment by alessiapacca** [comment]
@Ni55aN thanks a lot for your exhaustive answer. I agree that the solution should be individual. Do you think this behavior could be implemented as a simple customization, or should I implement this in a separate plugin?

**Comment by Ni55aN** [comment]
> Do you think this behavior could be implemented as a simple customization, or should I implement this in a separate plugin?

there is not much difference. The only benefit of the plugin is a single entry point so it can be easily enabled/disabled
